export interface ApiDataType {
	rentfaster_id: number;
	city: string;
	province: string;
	address: string;
	latitude: number;
	longitude: number;
	lease_term: number;
	type: string;
	price: number;
	beds: number;
	baths: number;
	sq_feet: number;
	furnishing: boolean;
	smoking: boolean;
	cats: boolean;
	dogs: boolean;
	location_freq: number;
	availability_days: number;
};