export interface RentalApiResponse {
  rentfaster_id: string;
  city: string;
  province: string;
  address: string;
  latitude: number;
  longitude: number;
  price: number;
  beds: number;
  baths: number;
  sq_feet: number;
  smoking: boolean;
  cats: boolean;
  dogs: boolean;
  location_freq: number;
  lease_term_months: number;
  type_apartment: boolean;
  type_basement: boolean;
  type_duplex: boolean;
  type_house: boolean;
  type_other: boolean;
  type_townhouse: boolean;
  furnishing_furnished: boolean;
  furnishing_negotiable: boolean;
  furnishing_unfurnished: boolean;
  availability_days: number;
};